### PR TITLE
Black improvement of the poem?

### PR DESCRIPTION
**Pull request by osmart**
see issue #3

What do you think David @MMunglah  ?

Please see https://canvas.anglia.ac.uk/courses/14266/discussion_topics/131076?module_item_id=713175 for what do next.

### CODE REVIEW

**Comment by MMunglah** [comment]
Are you happy with my changes to issue #3 and #4 ?

**Comment by MMunglah** [comment]
I also think Malevich's Black Square is an iconic painting, as I find **Suprematism** intriguing.

**Comment by MMunglah** [comment]
@osmart Is it okay for me to merge and close the issue?

**Review by osmart — COMMENTED** [review]
I have added another correction changing color to colour. Think this is a good idea

**Comment by MMunglah** [comment]
I will fix that right away.

**Comment by osmart** [comment]
Please can you merge the PR now?

**Comment by MMunglah** [comment]
Done.

**Comment by osmart** [comment]
> I will fix that right away.

I already have fixed in commit 
801f75e

GitHub PR mechanism is pretty neat - in my opinion it really facilitates joint working towards a fix

**Comment by MMunglah** [comment]
Sorry for the confusion. Thank you for noticing the spelling error.

**Comment by MMunglah** [comment]
Can I close the issue?

**Pull request merged**
